apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lRUzVsbnIzWjFvMzhpb1k0U3Nza2h1REFOQmdrcWhraUc5dzBCQVFzRkFEQmcKTVJVd0V3WURWUVFLRXd4amJIVnpkR1Z5TFhSbGJYQXhGVEFUQmdOVkJBTVRER05zZFhOMFpYSXRkR1Z0Y0RFdwpNQzRHQTFVRUJSTW5NVEF3TkRnNE5qSTBNRGt6TURBek5UZ3lOemcwTURRMU56QTNOakV5TWpFNE1EQTNPVGt5Ck1CNFhEVEl5TVRJd09UQTNNRFUwTUZvWERUTXlNVEl3TmpBM01EVTBNRm93WURFVk1CTUdBMVVFQ2hNTVkyeDEKYzNSbGNpMTBaVzF3TVJVd0V3WURWUVFERXd4amJIVnpkR1Z5TFhSbGJYQXhNREF1QmdOVkJBVVRKekV3TURRNApPRFl5TkRBNU16QXdNelU0TWpjNE5EQTBOVGN3TnpZeE1qSXhPREF3TnprNU1qQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMcEFDTkcyS1pjRkNFYmpxZHFjUk1OWDY0bkx5aURha29GdkhjVHYKN0lnZjV4d1Y3MnNSWUJraGdIckV5T0t1S3NDSjY3dzZvdzNzWFlkUUR4RnJneExjY2VibzBGTWRoMTJYb1hMegpvRnlYWVFjSzRXdEd1Sit3cWZ2SjR0R3NJcHlaRlV3UEJxYzNpdmlwVkdndWlUdzFKMHRyei9kaWZWTy8wVDg1CmtCUGpLcElFUmxlYk0yd2s0aTBUa01HVFhHMS9JWnRES1hOaHJtNFBHT3pTQXRuN1lubjROS2gveHhUY0ZSWVAKNTlKRUQ4MjBXVGUrUm9RSjNZRlNEWVp6WERIeVl6RHZOamljQWpyak1EeTkrajdxQnpXSnVrbWdIWGNCWEVhVQpMVG9DWks2MTluWXhsZm40ckRRZStyZXRCNWVmWEJReUdQSHFNb0lEdDFHYXo2c0NBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnR21NQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGQWdFd3B0K0krdmQKMEhQRGFzRTJURUFndEtXRk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1BYUW9Hb0c2WWpRZkp0c1UzU3ZlSgozUnY1YnNCcHVWajZFelc2TXBLQi8vWWExaFFHZ00zQXVOTDljdGZ3M0p1TTBsZHBxeWFoRGl2U3VCRHcwQTZBCnUwMEwwWVI5SXg4WktqZWlGbUNNckszL085VkJZK2JBRktzakVHbGVLZUVGelA4NG5FaDdJNmZaUjRUQllta28KeWhZSjJlOER0aUlBbzhtdHpsVlB6RVZGVEI3WVRQT0ZySE4xUWVwZWtZVTNHTUVrMmxaRE5rSDh0QkRaaWVWNwpudVVoNFVJWERhbDJibysrSkU2SFNORWFDaElSVldzd3A4UFBibEJzUStQWXF4eXJ5Tis2OXQ2TUFLdnRNQWZQCk9yZXMxejhnaW5lWEVESHBDb3ZVdnp6eE4xY2VoKzBUMXZXUWE3M3VnWDhZZFVVSUtKeUNwUW1HNG1MQnZwcGMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://tp.cc-syjung.com:3026
  name: cluster-temp
contexts:
- context:
    cluster: cluster-temp
    user: cluster-temp-cluster-temp
  name: cluster-temp-cluster-temp
- context:
    cluster: cluster-temp
    user: cluster-temp-temp1-cluster
  name: cluster-temp-temp1-cluster
current-context: cluster-temp-cluster-temp
kind: Config
preferences: {}
users:
- name: cluster-temp-cluster-temp
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --kube-cluster=cluster-temp
      - --teleport-cluster=cluster-temp
      - --proxy=tp.cc-syjung.com:443
      command: /usr/local/bin/tsh
      env: null
      provideClusterInfo: false
- name: cluster-temp-temp1-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kube
      - credentials
      - --kube-cluster=temp1-cluster
      - --teleport-cluster=cluster-temp
      - --proxy=tp.cc-syjung.com:443
      command: /usr/local/bin/tsh
      env: null
      provideClusterInfo: false
